фdded homework #1 (tasks 0-8) solution + unit-tests for each task
nesterrovv/tinkoff-backend-course pull request #1
Opened 2023-10-08 15:52 UTC by nesterrovv

Не добавлены юнит-тесты на задание №0 (как и написано в задании, т.к. нет смысла тестировать работу логгера). Также добавил собственный класс исключения, для его выбрасывания и обработки в случаях некорректных значений передаваемых аргументов (IncorrectArgumentException). ДЗ решал постепенно и каждое значимое изменение статуса ДЗ фиксировал дополнительным коммитом, насколько я знаю, так делать правильнее, надеюсь, это не повлияет на сложность проверки, если что, то готов это доработать. После каждого  push запускал вручную сборку из данной ветки, для возможности прохождения mvn package при ручном запуске добави указанное Александром изменение в пайплайн (на это тоже был отдельный комиит)

2023-10-10 20:17 UTC, Stasik371 commented
> Не добавлены юнит-тесты на задание №0 (как и написано в задании, т.к. нет смысла тестировать работу логгера). Также добавил собственный класс исключения, для его выбрасывания и обработки в случаях некорректных значений передаваемых аргументов (IncorrectArgumentException). ДЗ решал постепенно и каждое значимое изменение статуса ДЗ фиксировал дополнительным коммитом, насколько я знаю, так делать правильнее, надеюсь, это не повлияет на сложность проверки, если что, то готов это доработать. После каждого push запускал вручную сборку из данной ветки, для возможности прохождения mvn package при ручном запуске добави указанное Александром изменение в пайплайн (на это тоже был отдельный комиит)


Привет! Все круто, не переживай, делай как тебе удобно) Единственное, стоит настроить squash коммитов в мастер, чтоб итоговая картинка была красивой) 
Насчет кастомного исключения: Прикольно, это часто полезная вещь, но думаю, что тут бы тебе подошел `IllegalArgumentException` Исправлять не нужно, просто на будущее)

2023-10-10 20:22 UTC, nesterrovv commented
> > Не добавлены юнит-тесты на задание №0 (как и написано в задании, т.к. нет смысла тестировать работу логгера). Также добавил собственный класс исключения, для его выбрасывания и обработки в случаях некорректных значений передаваемых аргументов (IncorrectArgumentException). ДЗ решал постепенно и каждое значимое изменение статуса ДЗ фиксировал дополнительным коммитом, насколько я знаю, так делать правильнее, надеюсь, это не повлияет на сложность проверки, если что, то готов это доработать. После каждого push запускал вручную сборку из данной ветки, для возможности прохождения mvn package при ручном запуске добави указанное Александром изменение в пайплайн (на это тоже был отдельный комиит)
> 
> Привет! Все круто, не переживай, делай как тебе удобно) Единственное, стоит настроить squash коммитов в мастер, чтоб итоговая картинка была красивой) Насчет кастомного исключения: Прикольно, это часто полезная вещь, но думаю, что тут бы тебе подошел `IllegalArgumentException` Исправлять не нужно, просто на будущее)

Нужно откатить коммиты и сделать один уплотненный?

2023-10-10 21:04 UTC, Stasik371 requested changes

2023-10-10 21:04 UTC, Stasik371 commented on .github/workflows/build.yml
> +        if: ( github.event_name != 'workflow_dispatch' )
красавчик)

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +//    public static void main(String[] args) {}
Если не нужно, то удали)

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +//    public static void main(String[] args) {}
Тут и везде

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +    private final static Logger LOGGER = Logger.getLogger("LOGGER");
Есть душная специфкация, что правильно писать
```suggestion
    private static final Logger LOGGER = Logger.getLogger("LOGGER");
```

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +            LOGGER.warning(exception.getMessage());
Думаю в этом случае лучше писать в error, все-таки что-то неадекватное и непредвиденное в методе произошло)

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +    public int countNumberOfDigits(long number) {
Возможно тут стоит повесить модификатор static, но это на твой вкус)

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        long copy = number;
Вообще, эта строчка лишняя, потому что мы работаем с примитивом) Но вроде тоже чекстайл ругаться будет

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +                throw new IncorrectArgumentException();
В принципе, если сделать конструкор, то сюда можно будет передавать кастомное сообщение. Например так и написать: `число или сдвиг не может быть меньше нуля`

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +            result += Integer.parseInt(String.valueOf(binaryNumber.charAt(i))) * Math.pow(2, currentPowOfTwo);
Я аж уроки по информатике в школе вспомнил) Если задание не запрещает, то можно использовать 
`Integer.parseInt(binaryNumber, 2)`

2023-10-10 21:04 UTC, Stasik371 commented on src/main/java/edu/hw1/Task8.java
> +        int[] possibleRowMoves = {BIG_NEGATIVE_SHIFT, BIG_NEGATIVE_SHIFT, SMALL_NEGATIVE_SHIFT, SMALL_NEGATIVE_SHIFT,
Жесть конечно) Думаю в таком случае в константы выносить не нужно

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    }
Нужно приучиться писать тесты по методологии ААА, прочитать можно [здесь](https://habr.com/ru/articles/507594/)

Что хотелось бы видеть:
1. Один метод = один ТестКейс = один случай
2. Понятные названия методов из которых можно понять что происходит в тесте, например minutesToSeconds_shouldConvertIfToSecondsWithStandardValue (Мы в отделе делаем так, можно по-своему, но опять же, нужно передать суть)
3. Хочется комментариев с  `Arrange Act Assert`
4. Скорее всего для данного случая тебе подойдут параметризированные тесты: вот [тут](https://www.baeldung.com/parameterized-tests-junit-5) есть хорошая статейка)
5. Использовать [assertJ](https://www.baeldung.com/introduction-to-assertj), это вроде даже в условиях сказано) 
6. Модификатор public тут ставить не стоит, достаточно минималистичного void

Пример:
```suggestion
    @Test
    @DisplayName("minutesToSeconds переводит в секунды при корректных данных")
    void minutesToSeconds_shouldConvertIfToSecondsWithStandardValue() {
        //arrange
        String correctData = "13:56";
        
        //act
        int actual = task1.minutesToSeconds(correctData);
        
        //assert
        assertThat(actual).isEqualTo(13*60+56)
    }
```

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    }
Так нужно сделать везде)

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +        Assertions.assertEquals(4, task2.countNumberOfDigits(1234L));
Может отрицательных чиселок добавим?)

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        Assertions.assertTrue(task5.isPalindromeDescendant(11211230L));
Не очень понятно, что этот тест проверяет) Может комментарием допишем цепочку чисел, чтоб удостовериться, что из этого реально можно сделать палиндром)

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task6Test.java
> +        Assertions.assertEquals(5, task6.countK(6621));
Давай добавим тест на 4 одинаковых цифры. Например 1111, кое-что увидишь скорее всего)

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task7Test.java
> +        Assertions.assertEquals(-1, task7.rotateRight(-10, 10));
Можно в принципе не -1 кидать, а вызывать противоположный метод, но тут на твое усмотрение

2023-10-10 21:04 UTC, Stasik371 commented on src/test/java/edu/hw1/Task8Test.java
> +        Assertions.assertFalse((task8.knightBoardCapture(null)));
Лайк)

2023-10-10 21:59 UTC, nesterrovv commented on src/main/java/edu/hw1/Task2.java
> +        long copy = number;
Я понимаю, что передается копия, но чекстайл все же ругается, когда not-void класс меняет значение аргумента, поэтому пришлось добавлять "копировании копии" :(

2023-10-10 22:00 UTC, nesterrovv commented on src/main/java/edu/hw1/Task8.java
> +        int[] possibleRowMoves = {BIG_NEGATIVE_SHIFT, BIG_NEGATIVE_SHIFT, SMALL_NEGATIVE_SHIFT, SMALL_NEGATIVE_SHIFT,
Кодстайл не пускал -2, 2, 1, -1, но я еще раз попробую, может как-то все же можно внести будет

2023-10-11 12:42 UTC, nesterrovv commented on src/test/java/edu/hw1/Task7Test.java
> +        Assertions.assertEquals(-1, task7.rotateRight(-10, 10));
Подумал, что будет неочевидное поведение, когда в результате "некорреткного ввода" вызывается правый сдвиг вместо левого, поэтому решил кидать -1

2023-10-11 13:47 UTC, nesterrovv commented
Поправил все указанное, на непоправляемое (вроде необходимости по codestyle делать копию в том числе и примитива-аргумента или создавать "некрасивые" константы -- ответил комментарием в  PR. Тесты переписал на ААА с параметризацией, там где это уместно и через фреймворк assertJ, имена методам постарался дать более корректные. Модификатор public у тестов убрал

2023-10-15 17:36 UTC, Stasik371 commented
> > > Не добавлены юнит-тесты на задание №0 (как и написано в задании, т.к. нет смысла тестировать работу логгера). Также добавил собственный класс исключения, для его выбрасывания и обработки в случаях некорректных значений передаваемых аргументов (IncorrectArgumentException). ДЗ решал постепенно и каждое значимое изменение статуса ДЗ фиксировал дополнительным коммитом, насколько я знаю, так делать правильнее, надеюсь, это не повлияет на сложность проверки, если что, то готов это доработать. После каждого push запускал вручную сборку из данной ветки, для возможности прохождения mvn package при ручном запуске добави указанное Александром изменение в пайплайн (на это тоже был отдельный комиит)
> > 
> > 
> > Привет! Все круто, не переживай, делай как тебе удобно) Единственное, стоит настроить squash коммитов в мастер, чтоб итоговая картинка была красивой) Насчет кастомного исключения: Прикольно, это часто полезная вещь, но думаю, что тут бы тебе подошел `IllegalArgumentException` Исправлять не нужно, просто на будущее)
> 
> Нужно откатить коммиты и сделать один уплотненный?

Не) Думаю эта статейка тебе поможет) https://docs.github.com/ru/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

2023-10-15 17:37 UTC, Stasik371 commented on src/main/resources/project1/words.csv
> +medicine
Жесть) Если бы мог, поставил бы 5 из 3 баллов) Очень круто, что придумал

2023-10-15 18:06 UTC, nesterrovv commented on src/main/resources/project1/words.csv
> +medicine
Это для проекта по игре "Виселица", случайно внес в этот PR

2023-10-15 18:15 UTC, merged